hello/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.index, name = "index"),
    path("soumyadeep", views.soumyadeep, name = "soumyadeep"),
    path("<str:name>", views.greet, name = "greet")
]

lecture3/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks', include("tasks.urls"))
]

tasks/urls.py
from django.urls import path

from . import views
app_name = "tasks"
urlpatterns = [
    path("", views.index, name = "index"),
    path("add", views.add, name = "add")
]

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def soumyadeep(request):
    return HttpResponse("Hello Soumyadeep")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month==1 and now.date==1
    })

tasks/views.py
from django.shortcuts import render

tasks = ["foo", "bar", "baz"]
# Create your views here.
def index(request):
    return render(request, "tasks/index.html", {
        "tasks": tasks
    })

def add(request):
    return render(request, "tasks/add.html")

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            Hello
        </title>
    </head>
    <body>
        <h1>Hello, {{ name }}!</h1>
    </body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello!</title>
    </head>
    <body>
        Hello, world!
    </body>
</html>

newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Is it New Year's?</title>
        <link href = "{% static 'newyear/styles.css' %}" rel = "stylesheet">
    </head>
    <body>
        {% if newyear %}
            <h1>YES</h1>
        {% else %}
            <h1>NO</h1>
        {% endif %}
    </body>
</html>

tasks/templates/tasks/add.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        <h1>Add Task</h1>
        <form action = "{% url 'tasks:index' %}" method = "post">
            <input type = "text" name = "task">
            <input type = "submit">
        </form>
        <a href = "{% url 'tasks:index'%} ">See tasks</a>
    </body>
</html>

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}
        {%block body%}
        <ul>
            {%for task in tasks%}
                <li>{{task}}</li>
            {%endfor%}
        </ul>
        <a href = "{% url 'add'%}">Add a new task</a>
        {%endblock%}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {%block body%}
        {%endblock%}
    </body>
</html>